name: fds
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
